services:
  pki-2fa:
    container_name: pki-2fa-service
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      TZ: UTC
      STUDENT_PRIVATE: /app/student_private.pem
      DATA_DIR: /data

    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
